#!/usr/bin/env python 
# -*- coding: UTF-8 -*-
from dbfpy import dbf
import psycopg2
import datetime
import sys
import parus_id_to_odoo
def post_func(directory,dbname,userr,pas,hostt,portt):
	ank = dbf.Dbf(directory+"zkatper.dbf")
	f_ank = open(directory+'katper.csv', 'w')
	f_ank.write ("ID; CODE; NAME; NICK; NUM\n")
	#print len(ank)
	for i in ank:
		if i.deleted or i["KATPER_RN"] == None or i["CODE"] == None or i ["NAME"] == None or i ["NICK"] == None or i ["NUM"] == None:
			continue
		try:
			int(i["NUM"])
			f_ank.write ( "\""+str ( parus_id_to_odoo.parusIndexToOdoo ( i ["KATPER_RN"].decode('cp1251').encode('utf-8').decode('utf-8') )) +"\""+"; ")
			f_ank.write ( "\""+str ( i["CODE"]).decode('cp1251').encode('utf-8') +"\""+"; ")
			f_ank.write ( "\""+str ( i["NAME"]).decode('cp1251').encode('utf-8') +"\""+"; ")
			f_ank.write ( "\""+str ( i["NICK"]).decode('cp1251').encode('utf-8') +"\""+"; ")
			f_ank.write ( "\""+str ( i["NUM"]).decode('cp1251').encode('utf-8')  +"\""+"\n")
		except ValueError:
			print "fixed error in database katper int(i[\"NUM\"]) [ ok ]"

 	print "zank.dbf to katper.csv [ ok ]"
	f_ank.close()
	#CONNECT TO DATABASE
	con = psycopg2.connect(database=dbname, user=userr,password=pas,host=hostt,port=portt)
	cur = con.cursor()
	#cur.execute ("DELETE from tabel_ank;")
	
	#OPEN CSV FILE GENERATED BY syncronize.py script
	my_file = open(directory+'katper.csv')

	#CREATE TEMP TABLE
	cur.execute("CREATE TEMP TABLE tmp_z (ID int, CODE text, NAME text, NICK text, NUM int);")
	cur.copy_expert("COPY tmp_z FROM STDIN WITH DELIMITER ';' CSV HEADER;", my_file)

	#UPDATE DATA
	cur.execute("UPDATE tabel_katper SET  CODE=tmp_z.CODE, NAME=tmp_z.NAME, NICK=tmp_z.NICK FROM tmp_z WHERE  tabel_katper.id = tmp_z.id;")

	#INSERT DATA add something which lacks
	cur.execute("INSERT INTO tabel_katper (id, code, name, nick, num) SELECT T.id, T.CODE, T.NAME, T.NICK, T.NUM FROM tmp_z AS T LEFT JOIN tabel_katper AS P  ON T.id = P.id WHERE P.id IS NULL ;")

	#DROP TEMP TABLE or auto drop after session
	cur.execute("DROP TABLE tmp_z;")

	#CLOSE CONNECTION
	con.commit()
	cur.close()
	con.close()
	print "sql requests for katper table [ ok ]"


