#!/usr/bin/env python 
# -*- coding: UTF-8 -*-
from dbfpy import dbf
import psycopg2
import datetime
import sys
import parus_id_to_odoo
def pfcac_func(directory,dbname,userr,pas,hostt,portt):
	ank = dbf.Dbf(directory+"zfcacwth.dbf")
	f_ank = open(directory+'fcacwth.csv', 'w')
	f_ank.write ("ID; FCAC_RN; HRTYPE_RN; HOURQNT; DATE;\n")
	#print len(ank)
	for i in ank:
		if i.deleted or i["DATE"] == None or i ["FCAC_RN"] == None or  i ["HOURQNT"] == None or  i ["HRTYPE_RN"] == None or  i ["FCACWTH_RN"] == None  :
			continue
		f_ank.write ( str ( parus_id_to_odoo.parusIndexToOdoo ( i ["FCACWTH_RN"].decode('cp1251').encode('utf-8').decode('utf-8'))) +"; ")
		f_ank.write ( str ( parus_id_to_odoo.parusIndexToOdoo ( i ["FCAC_RN"].decode('cp1251').encode('utf-8').decode('utf-8')))  +"; ")
		f_ank.write ( str ( parus_id_to_odoo.parusIndexToOdoo ( i ["HRTYPE_RN"].decode('cp1251').encode('utf-8').decode('utf-8'))) +"; ")
		f_ank.write ( str ( i["HOURQNT"] )  + "; ")
		f_ank.write ( str( i["DATE"] ) + "\n")		         
	print "zfcacwth.dbf to fcacwth.csv [ ok ]"	
	f_ank.close()
	#CONNECT TO DATABASE
	con = psycopg2.connect(database=dbname, user=userr,password=pas,host=hostt,port=portt)
	cur = con.cursor()
	#cur.execute ("DELETE from tabel_fcacwth;")
	#OPEN CSV FILE GENERATED BY syncronize.py script
	my_file = open(directory+'fcacwth.csv')

	#CREATE TEMP TABLE
	cur.execute("CREATE TEMP TABLE tmp_z (ID int unique, FCAC_RN  int, HRTYPE_RN int, HOURQNT double precision, DATE date);") 
	cur.copy_expert("COPY tmp_z FROM STDIN WITH DELIMITER ';' CSV HEADER;", my_file)
	
	#UPDATE DATA
	cur.execute("UPDATE tabel_fcacwth SET  FCAC_RN=tmp_z.FCAC_RN, HRTYPE_RN=tmp_z.HRTYPE_RN, HOURQNT=tmp_z.HOURQNT, DATE=tmp_z.DATE FROM tmp_z WHERE  tabel_fcacwth.id = tmp_z.id;")

	#cur.execute("SELECT G.id, G.ANK_RN, G.POST_RN, G.SUBDIV_RN, G.VIDISP_RN, G.STARTDATE, G.ENDDATE FROM (SELECT T.id, T.ANK_RN, T.POST_RN, T.SUBDIV_RN, T.VIDISP_RN, T.STARTDATE, T.ENDDATE FROM tmp_z AS T LEFT JOIN tabel_fcac AS P  ON T.id = P.id WHERE P.id IS NULL) AS G, tabel_ank AS H where G.ank_rn = H.id  ;")
	#INSERT DATA add something which lacks.
	#add those records that are in the table tmp.z and not in the table fcacwth. And check that all the fields in the table fcac_rn existed fcac 
	cur.execute("INSERT INTO tabel_fcacwth (id, fcac_rn, hrtype_rn, hourqnt, date) SELECT G.id, G.FCAC_RN, G.HRTYPE_RN, G.HOURQNT, G.DATE FROM (SELECT T.id, T.FCAC_RN, T.HRTYPE_RN, T.HOURQNT, T.DATE FROM tmp_z AS T LEFT JOIN tabel_fcacwth AS P  ON T.id = P.id WHERE P.id IS NULL) AS G, tabel_fcac AS H where G.fcac_rn = H.id  ;")
	
	#rows = cur.fetchall()
	#for i in rows:
	#	print i
	#DROP TEMP TABLE or auto drop after session
	cur.execute("DROP TABLE tmp_z;")

	#CLOSE CONNECTION
	con.commit()
	cur.close()
	con.close()
	print "sql requests for table fcacwth [ ok ]"


